apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:    
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
      
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30011
  type: NodePort      
